version: '3.7'
services:
  api:
    image: node:14-buster
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ".:/home/node/app"
    command: node --trace-warnings main.js
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_USER=root
      - DB_PASSWORD=secret
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
