name: CI PR
on:
  pull_request:
    branches: [main]
jobs:
  prettier:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: npm ci --frozen-lockfile
      - run: npm run prettier
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: npm ci --frozen-lockfile
      - run: npm run test
