name: CI PR
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Prettier
        run: |
          npm ci --frozen-lockfile
          npm run prettier
